name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-main-ruby-2.7.2-${{ hashFiles('**/Gemfile.lock') }}
    - name: Lint with Rubocop
      run: |
        gem install bundler:1.17.3
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rubocop
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        rails_version: [5.2.5, 6.0.3.6, 6.1.3.1, main]
        ruby: [2.5, 2.6, 2.7, '3.0']
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Build and test with Rake
    - run: bundle exec rake
      env:
        RAILS_VERSION: ${{ matrix.rails_version }}
    - name: Upload coverage results
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: simplecov-resultset-rails${{matrix.rails_version}}-ruby${{matrix.ruby_version}}
        path: coverage
  coverage:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Download coverage results
      uses: actions/download-artifact@v2
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: gems-build-rails-main-ruby-2.7.2-${{ hashFiles('**/Gemfile.lock') }}
    - name: Collate simplecov
      run: |
        gem install bundler:1.17.3
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        bundle exec rake coverage:report

